-- CREATE TABLE NEWS(
--     ID BIGINT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
--     NEWS_URL NVARCHAR(256) NOT NULL,
--     POST_DATE DATETIME2 NOT NULL
-- );

-- CREATE TABLE DUSERS(
--     ID BIGINT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
--     USER_LOGIN NVARCHAR(32) NOT NULL,
--     USER_PASSWORD NVARCHAR(64) NOT NULL,
--     LAST_NEWS_ID BIGINT FOREIGN KEY REFERENCES NEWS(ID)
-- );

-- CREATE TABLE CONTACTS(
--     ID BIGINT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
--     CHAT_ID BIGINT NOT NULL,
--     USER_ID BIGINT NOT NULL FOREIGN KEY REFERENCES DUSERS(ID)
-- );

-- CREATE TABLE UNIVERSITY_SUBJECTS(
--     ID BIGINT PRIMARY KEY NOT NULL,
--     SUBJECT_NAME VARCHAR(100) NOT NULL
-- );