-- CREATE TABLE SUBJECTS(
--     ID BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
--     SUBJECT_NAME NVARCHAR(128) NOT NULL
-- );

-- CREATE TABLE TEACHERS(
--     ID BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
--     TEACHER_NAME NVARCHAR(128) NOT NULL
-- ); 

-- CREATE TABLE CLASSROOMS(
--     ID BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
--     CLASSROOM_NAME NVARCHAR(64) NOT NULL
-- ); 

-- CREATE TABLE LESSON_TIMES(
--     ID BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
--     START_TIME TIME NOT NULL,
--     END_TIME TIME NOT NULL
-- ); 

-- CREATE TABLE GROUPS(
--     ID BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
--     GROUP_NAME NVARCHAR(64) NOT NULL
-- ); 

-- CREATE TABLE LESSONS(
--     ID BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
--     SUBJECT_ID BIGINT NOT NULL FOREIGN KEY REFERENCES SUBJECTS(ID),
--     TEACHER_ID BIGINT NOT NULL FOREIGN KEY REFERENCES TEACHERS(ID),
--     LESSON_TIME_ID BIGINT NOT NULL FOREIGN KEY REFERENCES LESSON_TIMES(ID),
--     CLASSROOM_ID BIGINT NOT NULL FOREIGN KEY REFERENCES CLASSROOMS(ID),
--     GROUP_ID BIGINT NOT NULL FOREIGN KEY REFERENCES GROUPS(ID)
-- ); 